// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-9Q-I4Fndnd7Q8200EdbZSedylZtWhuE',
    appId: '1:363627873062:web:f94a6429face1c396c77e7',
    messagingSenderId: '363627873062',
    projectId: 'smart-hospital-queue-d287d',
    authDomain: 'smart-hospital-queue-d287d.firebaseapp.com',
    storageBucket: 'smart-hospital-queue-d287d.firebasestorage.app',
    measurementId: 'G-XB9H06GHD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTvESfNNTfjbLiguJn2d9SsXWnkEBoGdc',
    appId: '1:363627873062:android:35b22d83b3f358d16c77e7',
    messagingSenderId: '363627873062',
    projectId: 'smart-hospital-queue-d287d',
    storageBucket: 'smart-hospital-queue-d287d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztD2SzfLzXCcyZCS2xSGPqHOjMxEiWpQ',
    appId: '1:363627873062:ios:d1498c1fef3e7c296c77e7',
    messagingSenderId: '363627873062',
    projectId: 'smart-hospital-queue-d287d',
    storageBucket: 'smart-hospital-queue-d287d.firebasestorage.app',
    iosBundleId: 'com.hospital.smartHospitalQueueFlutter',
  );
}
